services:
  postgres:
    image: postgres:latest
    container_name: microservices_new
    environment:
      POSTGRES_USER: microuser
      POSTGRES_PASSWORD: micro123
      POSTGRES_DB: microservices_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    networks:
      - microservices-network

volumes:
  postgres_data:

networks:
  microservices-network:
    driver: bridge